# Generated by Django 5.1.4 on 2025-01-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='uploads/')),
                ('denoised_file', models.FileField(blank=True, null=True, upload_to='processed/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
